apiVersion: apps/v1
kind: Deployment
metadata:
  name: app-udbl-v1

spec:
  replicas: 2

  selector:
    matchLabels:
      app: app-udbl-v1

  template:
    metadata:
      labels:
        app: app-udbl-v1

    spec:
      containers:
      - name: app-udbl-v1
        image: umbadieudonne913/web-udbl:latest

        # Mot de passe en clair juste
        env:
        - name: DB_PASSWORD
          value: "password123"

        # Clé API en clair
        - name: API_KEY
          value: "sk-12345-abcde"

        ports:
        - containerPort: 80
