# Test du  webhook Synopkube - 29/06/2026 16:23
apiVersion: apps/v1
kind: Deployment
metadata:
  name: app-udbl-v1
  
spec:
  replicas: 1

  selector:
    matchLabels:
      app: app-udbl-v1

  template:
    metadata:
      labels:
        app: app-udbl-v1

    spec:
      containers:
      - name: app-udbl-v1
        image: umbadieudonne913/web-udbl:latest 

        ports:
        - containerPort: 80
